### ISSUE TITLE
Function for list all the available collection

### ISSUE THREAD

**Issue by mmikhan** [iconify/json-tools.js#2]
I am looking for a function that would return the available list of all sets something like `listIcons()` and couldn't find any. How do you get the list of all the available sets from [collections-json](https://github.com/iconify/collections-json)?

If that is something not available, is that something that can be considered to implement?

**Comment by cyberalien** [comment]
That function exists in `@iconify/json` package:

```js
// Install: npm install @iconify/json
const finder = require('@iconify/json');

const data = finder.collections();

// List all collection prefixes
console.log(Object.keys(data));

// Get information about one collection
console.log(data['mdi'])

// Locate JSON file
console.log(finder.locate('mdi'));
```

It is also available in PHP:

```php
<?php

// Installation: composer require iconify/json
use Iconify\IconsJSON\Finder;

$data = Finder::collections();

// List all collection prefixes
echo implode(', ', array_keys($data)), "\n";

// Get information about one collection
print_r($data['mdi']);

// Locate JSON file
echo Finder::locate('mdi'), "\n";
```


Added to todo list for documentation :)
